
- targets:
  - 'localhost:9090'
  labels:
    project: 'localhost'
    env: 'prometheus'

- targets:
  - 'webserver1:9100'
  labels:
    project: 'web1'
    env: 'ya_cloud_a'

- targets:
  - 'webserver2:9100'
  labels:
    project: 'web2'
    env: 'ya_cloud_b'
