- hosts: elasticsearch
  become: yes
  gather_facts: true
  tasks:

  - name: install elasticsearch
    ansible.builtin.apt:
      deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.9-amd64.deb

  - name: copy elasticsearch config file
    copy:
      src: ../config/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml

  - name: Make sure a service is running
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: elasticsearch
