---
- hosts: web
  become: yes
  gather_facts: true
  tasks:

    - name: Install prometheus-nginxlog-exporter_1.11.0
      ansible.builtin.apt:
       deb: 

    - name: config log format prometheus-nginxlog-exporter
      lineinfile:
       dest: /etc/prometheus-nginxlog-exporter.hcl
       regexp: '^\s* format'
#      line: '     format = "$remote_addr - [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" \"$request_length\" \"$upstream_response_time\" \"$request_time\""'
       line: '     format = "$remote_addr -$remote_user- [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""'
       backrefs: yes

    - name: Make sure a service prometheus-nginxlog-exporter is running
      systemd:
        state: started
        name: prometheus-nginxlog-exporter

    - name: enable service prometheus-nginxlog-exporter and ensure it is not masked
      systemd:
        name: prometheus-nginxlog-exporter
        enabled: yes
        masked: no
