---
- name: Configure webserver with nginx
  hosts: web
  become: true
  tasks:

    - name: "install nginx"
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: "copy config file"
      copy:
        src: ../config/nginx.conf
        dest: /etc/nginx/
      notify: restart nginx

    - name: copy nginx site.conf
      ansible.builtin.template:
        src: ../config/site.conf.j2
        dest: /etc/nginx/sites-enabled/
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: "copy website"
      copy:
        src: ../config/index.html.j2
        dest: /var/www/html/index.html

    - name: Check a status
      uri:
        url: http://localhost
        status_code: 200
        timeout: 30
      register: result
      failed_when: result.status != 200

    - name: Wait for the website to be available
      wait_for:
        host: localhost
        port: 80
        delay: 5
        timeout: 60

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
